apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: college-it
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: college-it
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: frontend
